---
- name: Systeem updates uitvoeren
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Basis software installeren
  ansible.builtin.apt:
    name: [curl, git, mergerfs, restic, ufw]
    state: present

- name: Tailscale installatiescript downloaden
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/install-tailscale.sh
    mode: '0700'

- name: Tailscale VPN installeren via script
  ansible.builtin.command: /tmp/install-tailscale.sh
  args:
    creates: /usr/bin/tailscale

- name: Tailscale activeren
  ansible.builtin.command: tailscale up --authkey={{ tailscale_key }}
  register: base_ts_out
  changed_when: "'already running' not in base_ts_out.stdout"

- name: Mappen maken voor data schijven
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: '0775'
  loop:
    - "/mnt/disk1"
    - "/mnt/disk2"
    - "{{ storage_merged }}"

- name: Map maken voor USB backup
  ansible.builtin.file:
    path: "{{ backup_usb.path }}"
    state: directory
    mode: '0755'

- name: USB Backup Stick permanent koppelen (nofail voorkomt boot issues)
  ansible.posix.mount:
    path: "{{ backup_usb.path }}"
    src: "{{ backup_usb.id }}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted

- name: Data schijven koppelen
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.id }}"
    fstype: ext4
    opts: defaults,noatime
    state: mounted
  loop: "{{ data_disks }}"

- name: MergerFS virtuele map configureren
  ansible.posix.mount:
    path: "{{ storage_merged }}"
    src: "/mnt/disk*"
    fstype: fuse.mergerfs
    opts: cache.files=partial,dropcacheonclose=true,category.create=epmfs
    state: mounted

- name: Scripts directory maken
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    mode: '0755'

- name: Restic backup script plaatsen
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /opt/scripts/backup.sh
    mode: '0700'

- name: Restic restore script plaatsen
  ansible.builtin.template:
    src: restore.sh.j2
    dest: /opt/scripts/restore.sh
    mode: '0700'

- name: Cronjob toevoegen voor Restic backup
  ansible.builtin.cron:
    name: "Dagelijkse Restic Backup"
    minute: "0"
    hour: "4"
    job: "/bin/bash /opt/scripts/backup.sh >> /var/log/restic.log 2>&1"
    user: root
