---
- name: Appdata en Media directorystructuur bouwen
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: '0775'
  loop:
    - "{{ appdata_dir }}"
    - "{{ storage_merged }}/data/torrents/tv"
    - "{{ storage_merged }}/data/torrents/movies"
    - "{{ storage_merged }}/data/media/tv"
    - "{{ storage_merged }}/data/media/movies"

- name: Interne .env file genereren voor Docker
  template:
    src: env.j2
    dest: "{{ appdata_dir }}/.env"

- name: Docker Compose file naar server kopiëren
  copy:
    src: ../../../../compose/docker-compose.yml
    dest: "{{ appdata_dir }}/docker-compose.yml"

- name: Volledige media stack opstarten
  community.docker.docker_compose_v2:
    project_src: "{{ appdata_dir }}"
    state: present
    pull: always