---
- name: Docker sleutel toevoegen
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Docker repository toevoegen
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    state: present

- name: Docker CE en Compose installeren
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    state: present
    update_cache: yes